PRAGMA foreign_keys=ON;
CREATE TABLE IF NOT EXISTS media (id TEXT PRIMARY KEY, name TEXT NOT NULL, logo_url TEXT, phone TEXT NOT NULL, whatsapp TEXT, description TEXT, commission_type TEXT DEFAULT 'none', commission_value REAL DEFAULT 0, password_hash TEXT NOT NULL, status TEXT DEFAULT 'active', created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS tuitions (id TEXT PRIMARY KEY, code TEXT NOT NULL UNIQUE, media_id TEXT, class_level TEXT NOT NULL, subjects TEXT NOT NULL, student_gender TEXT DEFAULT 'any', tuition_type TEXT NOT NULL, salary_type TEXT NOT NULL, salary_min INTEGER, salary_max INTEGER, salary_unit TEXT DEFAULT 'month', days_per_week INTEGER, time_text TEXT, division TEXT, district TEXT, thana TEXT, area TEXT, landmark TEXT, description TEXT, phone TEXT NOT NULL, whatsapp TEXT, status TEXT DEFAULT 'published', featured INTEGER DEFAULT 0, published_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, expires_at TEXT NOT NULL, views INTEGER DEFAULT 0, custom_fields TEXT DEFAULT '{}', FOREIGN KEY(media_id) REFERENCES media(id) ON DELETE SET NULL);
CREATE TABLE IF NOT EXISTS reports (id TEXT PRIMARY KEY, tuition_id TEXT NOT NULL, reason TEXT NOT NULL, details TEXT, status TEXT DEFAULT 'new', created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY(tuition_id) REFERENCES tuitions(id) ON DELETE CASCADE);
CREATE TABLE IF NOT EXISTS sessions (id TEXT PRIMARY KEY, role TEXT NOT NULL, media_id TEXT, expires_at TEXT NOT NULL, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS activity_logs (id TEXT PRIMARY KEY, actor_role TEXT NOT NULL, action TEXT NOT NULL, entity_type TEXT, entity_id TEXT, metadata TEXT, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS site_settings (key TEXT PRIMARY KEY, value TEXT NOT NULL);
CREATE INDEX IF NOT EXISTS idx_tuitions_status ON tuitions(status, published_at);
CREATE INDEX IF NOT EXISTS idx_tuitions_filters ON tuitions(division, district, thana, tuition_type, class_level);
