const json=(data,status=200)=>new Response(JSON.stringify(data),{status,headers:{'content-type':'application/json;charset=UTF-8','cache-control':'no-store'}});const id=()=>crypto.randomUUID();const clean=(s='')=>String(s).trim().slice(0,500);const auth=req=>(req.headers.get('authorization')||'').replace('Bearer ','');
const mapRow=t=>({...t,class_level:JSON.parse(t.classes_json||'[]').join(', ')||t.custom_class||'All classes',subjects:JSON.parse(t.subjects_json||'[]').join(', ')||t.custom_subject||'Various',division:t.city||'',district:t.city||'',area:t.area||'',salary_min:t.salary, salary_unit:'month',days_per_week:t.days_per_week,time_text:t.preferred_time||t.duration||'Flexible',phone:t.media_whatsapp||'',whatsapp:t.media_whatsapp||'',media_name:t.media_name==='TuitionBD Admin'?null:t.media_name});
async function adminSession(req,env){const token=auth(req);return token&&env.DB.prepare("SELECT * FROM sessions WHERE token_hash=? AND user_type='admin' AND expires_at>datetime('now')").bind(token).first()}
async function api(req,env){const u=new URL(req.url),p=u.pathname;
 if(req.method==='GET'&&p==='/api/health')return json({ok:true,app:env.APP_NAME||'Tuition Platform BD'});
 if(req.method==='GET'&&p==='/api/tuitions'){const q=u.searchParams,where=["t.status='available'","t.is_draft=0","t.expires_at>datetime('now')"],args=[];if(q.get('tuition_type')){where.push('t.tuition_type LIKE ?');args.push('%'+clean(q.get('tuition_type'))+'%')}if(q.get('q')){where.push('(t.code LIKE ? OR t.area LIKE ? OR t.city LIKE ? OR t.subjects_json LIKE ? OR t.classes_json LIKE ?)');const x='%'+clean(q.get('q'))+'%';args.push(x,x,x,x,x)}const {results}=await env.DB.prepare(`SELECT t.*,m.name AS account_name,m.logo_url FROM tuitions t LEFT JOIN media_accounts m ON m.id=t.media_id WHERE ${where.join(' AND ')} ORDER BY t.posted_at DESC LIMIT 60`).bind(...args).all();return json({items:(results||[]).map(mapRow)});}
 if(req.method==='GET'&&p.startsWith('/api/tuitions/')){const code=p.split('/')[3];const t=await env.DB.prepare('SELECT t.*,m.name AS account_name,m.logo_url FROM tuitions t LEFT JOIN media_accounts m ON m.id=t.media_id WHERE t.code=?').bind(code).first();if(!t)return json({error:'Not found'},404);return json({item:mapRow(t)});}
 if(req.method==='POST'&&p.startsWith('/api/tuitions/')&&p.endsWith('/reports')){const code=p.split('/')[3],b=await req.json(),t=await env.DB.prepare('SELECT id FROM tuitions WHERE code=?').bind(code).first();if(!t)return json({error:'Not found'},404);await env.DB.prepare('INSERT INTO reports(id,tuition_id,reason,details) VALUES(?,?,?,?)').bind(id(),t.id,clean(b.reason||'Other'),clean(b.details||'')).run();return json({ok:true},201);}
 if(req.method==='POST'&&p==='/api/auth/login'){const b=await req.json();if(b.username!=='admin'||!env.ADMIN_PASSWORD||b.password!==env.ADMIN_PASSWORD)return json({error:'Invalid credentials'},401);const token=id();await env.DB.prepare("INSERT INTO sessions(token_hash,user_type,user_id,username,expires_at) VALUES(?,?,?,?,datetime('now','+24 hours'))").bind(token,'admin',null,'admin').run();return json({token,role:'admin'});}
 if(req.method==='GET'&&p==='/api/admin/summary'){if(!await adminSession(req,env))return json({error:'Unauthorized'},401);const [t,m,r,v]=await Promise.all([env.DB.prepare("SELECT COUNT(*) c FROM tuitions WHERE status='available'").first(),env.DB.prepare('SELECT COUNT(*) c FROM media_accounts').first(),env.DB.prepare("SELECT COUNT(*) c FROM reports WHERE status='new'").first(),env.DB.prepare("SELECT COUNT(*) c FROM tuitions WHERE status='available'").first()]);return json({active_tuitions:t.c,media:m.c,new_reports:r?.c||0,total_tuitions:v.c});}
 return json({error:'Route not found'},404)}
export default{async fetch(req,env){if(new URL(req.url).pathname.startsWith('/api/')){try{return await api(req,env)}catch(e){return json({error:'Server error',detail:e.message},500)}}return env.ASSETS.fetch(req)}};