const json=(data,status=200)=>new Response(JSON.stringify(data),{status,headers:{'content-type':'application/json;charset=UTF-8','cache-control':'no-store'}});
const clean=(s='',n=500)=>String(s).trim().slice(0,n); const uid=()=>crypto.randomUUID(); const bearer=req=>(req.headers.get('authorization')||'').replace(/^Bearer\s+/,'');
async function hash(value){const b=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(String(value)));return [...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,'0')).join('')}
const row=t=>({...t,class_level:JSON.parse(t.classes_json||'[]').join(', ')||t.custom_class||'All classes',subjects:JSON.parse(t.subjects_json||'[]').join(', ')||t.custom_subject||'Various',division:t.city||'',district:t.city||'',area:t.area||'',salary_min:t.salary,salary_unit:'month',days_per_week:t.days_per_week,time_text:t.preferred_time||t.duration||'Flexible',phone:t.media_whatsapp||'',whatsapp:t.media_whatsapp||'',media_name:t.media_name==='TuitionBD Admin'?null:t.media_name});
async function session(req,env,roles=[]){const token=bearer(req);if(!token)return null;const s=await env.DB.prepare("SELECT * FROM sessions WHERE token_hash=? AND expires_at>datetime('now')").bind(token).first();return s&&(!roles.length||roles.includes(s.user_type))?s:null}
async function log(env,actor,action,type='',entity='',meta=''){await env.DB.prepare('INSERT INTO activity_logs(id,actor_role,action,entity_type,entity_id,metadata) VALUES(?,?,?,?,?,?)').bind(uid(),actor,action,type,String(entity),JSON.stringify(meta)).run()}
function tuitionInput(b,media){const classes=Array.isArray(b.classes)?b.classes:(b.class_level?[b.class_level]:[]),subjects=Array.isArray(b.subjects)?b.subjects:(b.subjects?[b.subjects]:[]);return {code:clean(b.code,40),city:clean(b.city||b.district||b.division,120),area:clean(b.area||b.thana,120),tuition_type:clean(b.tuition_type||'Home Tuition',60),classes_json:JSON.stringify(classes),custom_class:clean(b.custom_class,100),subjects_json:JSON.stringify(subjects),custom_subject:clean(b.custom_subject,150),medium:clean(b.medium,60),teacher_gender:clean(b.teacher_gender||'Any',30),special_requirement:clean(b.special_requirement,500),student_gender:clean(b.student_gender||'Any',30),student_count:Number(b.student_count)||null,days_per_week:Number(b.days_per_week)||null,duration:clean(b.duration,80),preferred_time:clean(b.preferred_time,100),salary:Number(b.salary)||null,negotiable:b.negotiable?1:0,media_id:media?.user_id||b.media_id||null,media_name:media?.username||b.media_name||'TuitionBD Admin',media_whatsapp:clean(b.whatsapp||b.phone,30),media_charge:clean(b.media_charge,100),charge_type:clean(b.charge_type,30),charge_amount:Number(b.charge_amount)||null,charge_basis:clean(b.charge_basis,40),posted_at:b.posted_at||new Date().toISOString(),expires_at:b.expires_at||new Date(Date.now()+15*86400000).toISOString(),updated_at:new Date().toISOString(),is_draft:b.is_draft?1:0,status:b.status||'available'} }
async function createTuition(env,b,s){const x=tuitionInput(b,s?.user_type==='media'?s:null);if(!x.code)return json({error:'Tuition code is required'},400);const exists=await env.DB.prepare('SELECT id FROM tuitions WHERE code=?').bind(x.code).first();if(exists)return json({error:'This tuition code already exists'},409);const keys=Object.keys(x), vals=Object.values(x);await env.DB.prepare(`INSERT INTO tuitions(${keys.join(',')}) VALUES(${keys.map(()=>'?').join(',')})`).bind(...vals).run();await log(env,s?.user_type||'admin','create','tuition',x.code);return json({ok:true,code:x.code},201)}
async function api(req,env){const u=new URL(req.url),p=u.pathname,m=req.method;
 if(m==='GET'&&p==='/api/health')return json({ok:true,app:env.APP_NAME||'Tuition Platform BD'});
 if(m==='GET'&&p==='/api/tuitions'){const q=u.searchParams,w=["t.status='available'","t.is_draft=0","t.expires_at>datetime('now')"],a=[];if(q.get('q')){w.push('(t.code LIKE ? OR t.area LIKE ? OR t.city LIKE ? OR t.subjects_json LIKE ? OR t.classes_json LIKE ?)');const x='%'+clean(q.get('q'))+'%';a.push(x,x,x,x,x)}if(q.get('tuition_type')){w.push('t.tuition_type LIKE ?');a.push('%'+clean(q.get('tuition_type'))+'%')}const r=await env.DB.prepare(`SELECT t.*,m.name account_name,m.logo_url FROM tuitions t LEFT JOIN media_accounts m ON m.id=t.media_id WHERE ${w.join(' AND ')} ORDER BY t.posted_at DESC LIMIT 60`).bind(...a).all();return json({items:(r.results||[]).map(row)});}
 if(m==='GET'&&p.startsWith('/api/tuitions/')){const code=p.split('/')[3],t=await env.DB.prepare('SELECT t.*,m.name account_name,m.logo_url FROM tuitions t LEFT JOIN media_accounts m ON m.id=t.media_id WHERE t.code=?').bind(code).first();return t?json({item:row(t)}):json({error:'Not found'},404)}
 if(m==='POST'&&p.endsWith('/reports')){const code=p.split('/')[3],b=await req.json(),t=await env.DB.prepare('SELECT id FROM tuitions WHERE code=?').bind(code).first();if(!t)return json({error:'Not found'},404);await env.DB.prepare('INSERT INTO reports(id,tuition_id,reason,details) VALUES(?,?,?,?)').bind(uid(),t.id,clean(b.reason||'Other'),clean(b.details||'')).run();return json({ok:true},201)}
 if(m==='POST'&&p==='/api/auth/login'){const b=await req.json(),role=b.role==='media'?'media':'admin';if(role==='admin'){if(b.username!=='admin'||!env.ADMIN_PASSWORD||b.password!==env.ADMIN_PASSWORD)return json({error:'Invalid credentials'},401);const token=uid();await env.DB.prepare("INSERT INTO sessions(token_hash,user_type,user_id,username,expires_at) VALUES(?,?,?,?,datetime('now','+24 hours'))").bind(token,'admin',null,'admin').run();return json({token,role})}const account=await env.DB.prepare('SELECT * FROM media_accounts WHERE username=? AND enabled=1').bind(clean(b.username,80)).first();if(!account||account.password_hash!==(await hash(b.password)))return json({error:'Invalid media credentials'},401);const token=uid();await env.DB.prepare("INSERT INTO sessions(token_hash,user_type,user_id,username,expires_at) VALUES(?,?,?,?,datetime('now','+24 hours'))").bind(token,'media',account.id,account.username).run();return json({token,role,media_id:account.id})}
 const s=await session(req,env,['admin','media']);
 if(m==='POST'&&p==='/api/admin/tuitions'){if(!s||s.user_type!=='admin')return json({error:'Unauthorized'},401);return createTuition(env,await req.json(),s)}
 if(m==='POST'&&p==='/api/media/tuitions'){if(!s||s.user_type!=='media')return json({error:'Unauthorized'},401);return createTuition(env,await req.json(),s)}
 if(p==='/api/admin/summary'&&m==='GET'){if(!s||s.user_type!=='admin')return json({error:'Unauthorized'},401);const [t,mx,r,v,e]=await Promise.all([env.DB.prepare("SELECT COUNT(*) c FROM tuitions").first(),env.DB.prepare('SELECT COUNT(*) c FROM media_accounts').first(),env.DB.prepare("SELECT COUNT(*) c FROM reports WHERE status='new'").first(),env.DB.prepare("SELECT COALESCE(SUM(CASE WHEN status!='deleted' THEN 1 ELSE 0 END),0) c FROM tuitions").first(),env.DB.prepare("SELECT COUNT(*) c FROM tuitions WHERE expires_at<=datetime('now','+3 days') AND status='available'").first()]);return json({total_tuitions:t.c,media:mx.c,new_reports:r?.c||0,active_tuitions:v.c,expiring_soon:e.c})}
 if(p==='/api/admin/tuitions'&&m==='GET'){if(!s||s.user_type!=='admin')return json({error:'Unauthorized'},401);const r=await env.DB.prepare('SELECT * FROM tuitions ORDER BY posted_at DESC LIMIT 200').all();return json({items:r.results||[]})}
 if(p.startsWith('/api/admin/tuitions/')&&m==='PATCH'){if(!s||s.user_type!=='admin')return json({error:'Unauthorized'},401);const code=p.split('/')[4],b=await req.json(),allowed=['status','is_draft','featured','expires_at','special_requirement','salary','area','city','tuition_type'];const sets=[],a=[];for(const k of allowed)if(b[k]!==undefined){sets.push(`${k}=?`);a.push(b[k])}if(!sets.length)return json({error:'No changes'},400);a.push(code);await env.DB.prepare(`UPDATE tuitions SET ${sets.join(',')},updated_at=datetime('now') WHERE code=?`).bind(...a).run();await log(env,'admin','update','tuition',code,b);return json({ok:true})}
 if(p.startsWith('/api/admin/tuitions/')&&m==='DELETE'){if(!s||s.user_type!=='admin')return json({error:'Unauthorized'},401);const code=p.split('/')[4];await env.DB.prepare("UPDATE tuitions SET status='deleted',updated_at=datetime('now') WHERE code=?").bind(code).run();await log(env,'admin','delete','tuition',code);return json({ok:true})}
 if(p==='/api/admin/reports'&&m==='GET'){if(!s||s.user_type!=='admin')return json({error:'Unauthorized'},401);const r=await env.DB.prepare('SELECT r.*,t.code FROM reports r LEFT JOIN tuitions t ON t.id=r.tuition_id ORDER BY r.created_at DESC').all();return json({items:r.results||[]})}
 if(p.startsWith('/api/admin/reports/')&&m==='PATCH'){if(!s||s.user_type!=='admin')return json({error:'Unauthorized'},401);const b=await req.json();await env.DB.prepare('UPDATE reports SET status=? WHERE id=?').bind(clean(b.status||'resolved',30),p.split('/')[4]).run();return json({ok:true})}
 if(p==='/api/admin/media'&&m==='GET'){if(!s||s.user_type!=='admin')return json({error:'Unauthorized'},401);const r=await env.DB.prepare('SELECT id,name,username,logo_url,whatsapp,enabled,is_verified,created_at FROM media_accounts ORDER BY created_at DESC').all();return json({items:r.results||[]})}
 if(p==='/api/admin/media'&&m==='POST'){if(!s||s.user_type!=='admin')return json({error:'Unauthorized'},401);const b=await req.json();if(!b.name||!b.username||!b.password)return json({error:'Name, username and password required'},400);try{await env.DB.prepare('INSERT INTO media_accounts(name,username,password_hash,logo_url,whatsapp,enabled,is_verified) VALUES(?,?,?,?,?,?,?)').bind(clean(b.name,100),clean(b.username,80),await hash(b.password),clean(b.logo_url,500),clean(b.whatsapp,30),1,1).run();await log(env,'admin','create','media',b.username);return json({ok:true},201)}catch(e){return json({error:'Username already exists'},409)}}
 if(p.startsWith('/api/admin/media/')&&m==='PATCH'){if(!s||s.user_type!=='admin')return json({error:'Unauthorized'},401);const idn=p.split('/')[4],b=await req.json();if(b.password)b.password_hash=await hash(b.password),delete b.password;const allowed=['name','logo_url','whatsapp','enabled','is_verified','password_hash'],sets=[],a=[];for(const k of allowed)if(b[k]!==undefined){sets.push(`${k}=?`);a.push(b[k])}a.push(idn);await env.DB.prepare(`UPDATE media_accounts SET ${sets.join(',')} WHERE id=?`).bind(...a).run();return json({ok:true})}
 if(p==='/api/media/summary'&&m==='GET'){if(!s||s.user_type!=='media')return json({error:'Unauthorized'},401);const [a,e]=await Promise.all([env.DB.prepare("SELECT COUNT(*) c FROM tuitions WHERE media_id=? AND status='available'").bind(s.user_id).first(),env.DB.prepare("SELECT COUNT(*) c FROM tuitions WHERE media_id=? AND expires_at<=datetime('now')").bind(s.user_id).first()]);return json({active_posts:a.c,expired_posts:e.c})}
 if(p==='/api/media/tuitions'&&m==='GET'){if(!s||s.user_type!=='media')return json({error:'Unauthorized'},401);const r=await env.DB.prepare('SELECT * FROM tuitions WHERE media_id=? ORDER BY posted_at DESC').bind(s.user_id).all();return json({items:r.results||[]})}
 if(p.startsWith('/api/media/tuitions/')&&m==='DELETE'){if(!s||s.user_type!=='media')return json({error:'Unauthorized'},401);await env.DB.prepare("UPDATE tuitions SET status='deleted',updated_at=datetime('now') WHERE code=? AND media_id=?").bind(p.split('/')[4],s.user_id).run();return json({ok:true})}
 if(p==='/api/admin/logs'&&m==='GET'){if(!s||s.user_type!=='admin')return json({error:'Unauthorized'},401);const r=await env.DB.prepare('SELECT * FROM activity_logs ORDER BY created_at DESC LIMIT 200').all();return json({items:r.results||[]})}
 return json({error:'Route not found'},404)}
export default{async fetch(req,env){if(new URL(req.url).pathname.startsWith('/api/')){try{return await api(req,env)}catch(e){return json({error:'Server error',detail:e.message},500)}}return env.ASSETS.fetch(req)}};